; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_astropill_intro=music_data_astropill_intro
.endif

music_data_astropill_intro:
	.byte 1
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4 ; 00 : Song 1
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_astropill_intro
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env3,@env0 ; 00 : Duty 0

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song0ref5:
	.byte $ff, $ff, $ff, $ff, $47, $ff, $ff, $ff, $ff, $47, $ff, $ff, $ff, $ff, $47, $ff, $ff, $ff, $ff, $47
	.byte $41, $10
	.word @song0ref5
	.byte $47
	.byte $41, $10
	.word @song0ref5
	.byte $47
	.byte $41, $10
	.word @song0ref5
	.byte $47
	.byte $41, $10
	.word @song0ref5
	.byte $47
	.byte $41, $10
	.word @song0ref5
	.byte $47
	.byte $41, $10
	.word @song0ref5
	.byte $47, $ff, $ff, $ff, $ff, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $80
@song0ref58:
	.byte $16, $ff, $9d, $1d, $cd, $16, $cd, $18, $ff, $9d, $1d, $9d, $ff, $19, $ff, $9d, $1d, $cd, $19, $cd, $1b, $bd, $df, $1d
	.byte $cd, $1b, $cd, $16, $ff, $9d, $1d, $cd, $16, $8d
@song0ref92:
	.byte $bf, $00, $ff, $ff, $ff, $bd
@song0ref98:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $41, $40
	.word @song0ref58
	.byte $41, $3c
	.word @song0ref58
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80
@song0ref133:
	.byte $12, $ff, $ff, $bd, $14, $ff, $bd, $ff, $16, $ff, $ff, $bd, $14, $bd, $ff, $ff, $12, $ff, $fd
	.byte $41, $1e
	.word @song0ref92
	.byte $41, $13
	.word @song0ref133
	.byte $41, $1e
	.word @song0ref92
	.byte $41, $13
	.word @song0ref133
	.byte $41, $1a
	.word @song0ref92
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $41, $18
	.word @song0ref98
	.byte $41, $18
	.word @song0ref98
	.byte $41, $18
	.word @song0ref98
	.byte $41, $18
	.word @song0ref98
	.byte $41, $14
	.word @song0ref98
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $18
	.word @song0ref98
	.byte $41, $18
	.word @song0ref98
	.byte $41, $18
	.word @song0ref98
	.byte $41, $18
	.word @song0ref98
	.byte $41, $14
	.word @song0ref98
	.byte $42
	.word @song0ch4loop
